### ISSUE TITLE
demo code at plunker or codepen working?

### ISSUE THREAD

**Issue by sentient** [saburab/angular-schema-form-nwp-file-upload#2]
I tried the drop file at http://codepen.io/sufius/pen/MaNQrY
and http://plnkr.co/edit/sboEMnUj5mzoyS2wqy4F?p=preview

but I don't see much action yet.  
Also the 'open file browser' did not show an error when I selected a .PDF file. (just testing the error handling)

Can you confirm with which browser it works for you? 
I tried with Chrome on Win10  and also Chrome on Ubuntu

**Comment by sufius** [comment]
yes, u r right. i will try to find time to fix it in the next days.

**Comment by saburab** [comment]
in codepen u need for such a scenario a premium account. maybe there is the same problem with plunkr. at least i updated the attached index.html file. So u are able to see a working example by opening the index.html file in a browser with an active internet connection. hope this answer resolved your question.
