### ISSUE TITLE
how do get a model value after file upload done ?

### ISSUE THREAD

**Issue by sureshamk** [saburab/angular-schema-form-nwp-file-upload#4]
i can upload the file and I could see the json response, But i could not see any updates on model of schemaform .. Any idea ?

**Comment by nevace** [comment]
+1

**Comment by saburab** [comment]
if i got it correct, u want to see the uploaded file in the schema form preview?

u could programmaticly put the following piece of code to your form-model after successfully submitted and received the file infos in the json block.

```
 {
      type: "template",
      template: '<a href="json_response_file_url">{{json_response_file_title}}!</a>',
      name: 'uploadedFile'
 },
```

**Comment by nevace** [comment]
If it's the same issue as me, I have no idea how to get the response into my schema form model. If I log the response from: 

```
file.upload.then(function(response) {
              $timeout(function() {
                file.result = response.data;
              });
```

I see my response data. I just assumed it would be attached to the schema model but it's not there. 

Thanks

**Comment by sureshamk** [comment]
Is possible to attach with Schema Model , it would more helpfull @saburab @nevace , once file upload done with response data like file uploaded url . I dont have idea to do .

**Comment by nevace** [comment]
I added it to the model #5

**Comment by saburab** [comment]
merged, thank you guys :thumbsup:
